name: loc_example
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5
  - aom=3.6.0
  - asttokens=3.0.0
  - binutils_impl_win-64=2.44
  - binutils_win-64=2.44
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - cairo=1.16.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - cmdstan=2.36.0
  - cmdstanpy=1.2.5
  - colorama=0.4.6
  - comm=0.2.2
  - cuda-cccl=12.4.127
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-opencl=12.4.127
  - cuda-opencl-dev=12.4.127
  - cuda-profiler-api=12.4.127
  - cuda-runtime=11.8.0
  - dav1d=1.2.1
  - debugpy=1.8.11
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - filelock=3.17.0
  - fontconfig=2.14.1
  - freeglut=3.4.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - gcc_impl_win-64=13.3.0
  - gcc_win-64=13.3.0
  - gendef=v12.0.0.r1.ggdc42231f0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - gxx_impl_win-64=13.3.0
  - gxx_win-64=13.3.0
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.7.0
  - intel-openmp=2025.0.0
  - ipykernel=6.29.5
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_win-64=2.44
  - lerc=4.0.0
  - libavif=1.1.1
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.5.147
  - libcurand-dev=10.3.5.147
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-devel_win-64=13.3.0
  - libglib=2.84.2
  - libgomp=15.1.0
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libsodium=1.0.20
  - libstdcxx=15.1.0
  - libstdcxx-devel_win-64=13.3.0
  - libtiff=4.7.0
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - m2-bash=5.2.037.2
  - m2-conda-epoch=20250515
  - m2-coreutils=8.32.5
  - m2-filesystem=2025.02.23.1
  - m2-gcc-libs=13.3.0.1
  - m2-gmp=6.3.0.1
  - m2-libiconv=1.18.1
  - m2-libintl=0.22.5.1
  - m2-make=4.4.1.2
  - m2-msys2-runtime=3.6.1.4
  - m2-sed=4.9.1
  - m2w64-sysroot_win-64=12.0.0.r4.gg4f2fc60ca
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mingw-w64-ucrt-x86_64-crt-git=12.0.0.r4.gg4f2fc60ca
  - mingw-w64-ucrt-x86_64-headers-git=12.0.0.r4.gg4f2fc60ca
  - mingw-w64-ucrt-x86_64-windows-default-manifest=6.4
  - mingw-w64-ucrt-x86_64-winpthreads-git=12.0.0.r4.gg4f2fc60ca
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numexpr=2.10.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.5.1
  - packaging=25.0
  - parso=0.8.4
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.1
  - pixman=0.46.4
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=5.9.0
  - pure_eval=0.2.3
  - pycparser=2.21
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pywin32=308
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - requests=2.32.4
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - stanio=0.5.1
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - bayesflow==2.0.5
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.58.5
      - h5py==3.14.0
      - keras==3.10.0
      - kiwisolver==1.4.8
      - markdown-it-py==3.0.0
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - namex==0.1.0
      - numpy==1.26.4
      - optree==0.16.0
      - pandas==2.3.0
      - pyparsing==3.2.3
      - rich==14.0.0
      - scipy==1.16.0
      - seaborn==0.13.2
      - torchaudio==2.5.1
      - torchvision==0.20.1